theme: "jekyll-theme-cayman"
title: "Tondovo portfolio"
title_separator: "-"
tagline: "Your sidekick in using GitHub Pages and blogs"
description: "Zde je pár mých projektů, kterými bych se chtěl pochlubit."
repository: "github.com/tonikhorkel"
