theme: jekyll-theme-cayman
page:
  title: Tondovo portfolio
   description: Zde je pár mých projektů, kterými bych se chtěl pochlubit.
show_downloads: false
github: 
  repository_url: https://github.com/TonikHorkel
  owner_name: Tonda Horkel
