theme: jekyll-theme-cayman
title: Tondovo portfolio
description: Zde je pár mých projektů, kterými bych se chtěl pochlubit.
avatar: https://avatars.githubusercontent.com/u/59200680?v=4
round-avatar: true
