theme: jekyll-theme-cayman
lang: cs
# title: Tondovo portfolio
# description: Zde je pár mých projektů, kterými bych se chtěl pochlubit.
show_downloads: false
github:
  repository_name: This page
  repository_url: https://github.com/TonikHorkel
  owner_name: Tonda Horkel
